version: "3"
services:
  kudu-master-1:
    image: apache/kudu:1.17
    ports:
      - "7051:7051"
      - "8051:8051"
    command: ["master"]
    volumes:
      - kudu-master-1:/var/lib/kudu
    environment:
      - KUDU_MASTERS=kudu-master-1:7051,kudu-master-2:7151
      - >
        MASTER_ARGS=--fs_wal_dir=/var/lib/kudu/master
        --rpc_bind_addresses=0.0.0.0:7051
        --webserver_port=8051
        --use_hybrid_clock=false
        --unlock_unsafe_flags=true
    networks:
      - kudu-network
  kudu-master-2:
    image: apache/kudu:1.17
    ports:
      - "7151:7151"
      - "8151:8151"
    command: ["master"]
    volumes:
      - kudu-master-2:/var/lib/kudu
    environment:
      - KUDU_MASTERS=kudu-master-1:7051,kudu-master-2:7151
      - >
        MASTER_ARGS=--fs_wal_dir=/var/lib/kudu/master
        --rpc_bind_addresses=0.0.0.0:7151
        --webserver_port=8151
        --use_hybrid_clock=false
        --unlock_unsafe_flags=true
    networks:
      - kudu-network
  kudu-tserver-1:
    image: apache/kudu:1.17
    depends_on:
      - kudu-master-1
      - kudu-master-2
    ports:
      - "7050:7050"
      - "8050:8050"
    command: ["tserver"]
    volumes:
      - kudu-tserver-1:/var/lib/kudu
    environment:
      - KUDU_MASTERS=kudu-master-1:7051,kudu-master-2:7151
      - >
        TSERVER_ARGS=--fs_wal_dir=/var/lib/kudu/tserver
        --rpc_bind_addresses=0.0.0.0:7050
        --webserver_port=8050
        --use_hybrid_clock=false
        --unlock_unsafe_flags=true
    networks:
      - kudu-network
  kudu-tserver-2:
    image: apache/kudu:1.17
    depends_on:
      - kudu-master-1
      - kudu-master-2
    ports:
      - "7150:7150"
      - "8150:8150"
    command: ["tserver"]
    volumes:
      - kudu-tserver-2:/var/lib/kudu
    environment:
      - KUDU_MASTERS=kudu-master-1:7051,kudu-master-2:7151
      - >
        TSERVER_ARGS=--fs_wal_dir=/var/lib/kudu/tserver
        --rpc_bind_addresses=0.0.0.0:7150
        --webserver_port=8150
        --use_hybrid_clock=false
        --unlock_unsafe_flags=true
    networks:
      - kudu-network

volumes:
  kudu-master-1:
  kudu-master-2:
  kudu-tserver-1:
  kudu-tserver-2:

networks:
  kudu-network:
    driver: bridge
