version: '3.9'
services:
  mysql-master:
    image: mysql:8.0
    container_name: mysql-master
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_REPLICATION_USER: replica
      MYSQL_REPLICATION_PASSWORD: replica
      MYSQL_DATABASE: test
      TZ: Asia/Seoul
    ports:
      - "3306:3306"
    volumes:
      - master-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password --server-id=1 --log-bin=mysql-bin

  mysql-slave:
    image: mysql:8.0
    container_name: mysql-slave
    environment:
      MYSQL_ROOT_PASSWORD: admin
      TZ: Asia/Seoul
    ports:
      - "3307:3306"
    depends_on:
      - mysql-master
    volumes:
      - slave-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password --server-id=2 --relay-log=relay-bin --read-only=1

volumes:
  master-data:
  slave-data: