version: "3"

services:
  jobmanager:
    image: flink:1.19
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager        
    networks:
      - flink-network
  taskmanager:
    image: flink:1.19
    depends_on:
      - jobmanager
    command: taskmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 2
    networks:
      - flink-network

networks:
  flink-network:
    driver: bridge
